from .example_model_delete import ExampleModelDeleteView
from .example_model_update import ExampleModelUpdateView
from .example_model_detail import ExampleModelDetailView
from .example_model_create import ExampleModelCreateView
from .example_model_list import ExampleModelListView
