from .example_model import ExampleModelDeleteTestCase
from .example_model import ExampleModelUpdateTestCase
from .example_model import ExampleModelDetailTestCase
from .example_model import ExampleModelCreateTestCase
from .example_model import ExampleModelListTestCase
